package cn.com.jnpc.foreign.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FiForeignerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public FiForeignerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(int value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(int value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(int value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(int value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(int value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(int value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(int value1, int value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(int value1, int value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(int value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(int value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(int value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(int value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(int value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(int value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(int value1, int value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(int value1, int value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("COUNTRY =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("COUNTRY <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("COUNTRY like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("COUNTRY not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("COUNTRY in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentIsNull() {
            addCriterion("COMPANY_DEPARTMENT is null");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentIsNotNull() {
            addCriterion("COMPANY_DEPARTMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentEqualTo(String value) {
            addCriterion("COMPANY_DEPARTMENT =", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentNotEqualTo(String value) {
            addCriterion("COMPANY_DEPARTMENT <>", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentGreaterThan(String value) {
            addCriterion("COMPANY_DEPARTMENT >", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_DEPARTMENT >=", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentLessThan(String value) {
            addCriterion("COMPANY_DEPARTMENT <", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_DEPARTMENT <=", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentLike(String value) {
            addCriterion("COMPANY_DEPARTMENT like", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentNotLike(String value) {
            addCriterion("COMPANY_DEPARTMENT not like", value, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentIn(List<String> values) {
            addCriterion("COMPANY_DEPARTMENT in", values, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentNotIn(List<String> values) {
            addCriterion("COMPANY_DEPARTMENT not in", values, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentBetween(String value1, String value2) {
            addCriterion("COMPANY_DEPARTMENT between", value1, value2, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andCompanyDepartmentNotBetween(String value1, String value2) {
            addCriterion("COMPANY_DEPARTMENT not between", value1, value2, "companyDepartment");
            return (Criteria) this;
        }

        public Criteria andPassportIdIsNull() {
            addCriterion("PASSPORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPassportIdIsNotNull() {
            addCriterion("PASSPORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPassportIdEqualTo(String value) {
            addCriterion("PASSPORT_ID =", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotEqualTo(String value) {
            addCriterion("PASSPORT_ID <>", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdGreaterThan(String value) {
            addCriterion("PASSPORT_ID >", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdGreaterThanOrEqualTo(String value) {
            addCriterion("PASSPORT_ID >=", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdLessThan(String value) {
            addCriterion("PASSPORT_ID <", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdLessThanOrEqualTo(String value) {
            addCriterion("PASSPORT_ID <=", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdLike(String value) {
            addCriterion("PASSPORT_ID like", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotLike(String value) {
            addCriterion("PASSPORT_ID not like", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdIn(List<String> values) {
            addCriterion("PASSPORT_ID in", values, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotIn(List<String> values) {
            addCriterion("PASSPORT_ID not in", values, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdBetween(String value1, String value2) {
            addCriterion("PASSPORT_ID between", value1, value2, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotBetween(String value1, String value2) {
            addCriterion("PASSPORT_ID not between", value1, value2, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateIsNull() {
            addCriterion("PASSPORT_EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateIsNotNull() {
            addCriterion("PASSPORT_EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateEqualTo(Date value) {
            addCriterion("PASSPORT_EXP_DATE =", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateNotEqualTo(Date value) {
            addCriterion("PASSPORT_EXP_DATE <>", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateGreaterThan(Date value) {
            addCriterion("PASSPORT_EXP_DATE >", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PASSPORT_EXP_DATE >=", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateLessThan(Date value) {
            addCriterion("PASSPORT_EXP_DATE <", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateLessThanOrEqualTo(Date value) {
            addCriterion("PASSPORT_EXP_DATE <=", value, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateIn(List<Date> values) {
            addCriterion("PASSPORT_EXP_DATE in", values, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateNotIn(List<Date> values) {
            addCriterion("PASSPORT_EXP_DATE not in", values, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateBetween(Date value1, Date value2) {
            addCriterion("PASSPORT_EXP_DATE between", value1, value2, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPassportExpDateNotBetween(Date value1, Date value2) {
            addCriterion("PASSPORT_EXP_DATE not between", value1, value2, "passportExpDate");
            return (Criteria) this;
        }

        public Criteria andPostIsNull() {
            addCriterion("POST is null");
            return (Criteria) this;
        }

        public Criteria andPostIsNotNull() {
            addCriterion("POST is not null");
            return (Criteria) this;
        }

        public Criteria andPostEqualTo(String value) {
            addCriterion("POST =", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotEqualTo(String value) {
            addCriterion("POST <>", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThan(String value) {
            addCriterion("POST >", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThanOrEqualTo(String value) {
            addCriterion("POST >=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThan(String value) {
            addCriterion("POST <", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThanOrEqualTo(String value) {
            addCriterion("POST <=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLike(String value) {
            addCriterion("POST like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotLike(String value) {
            addCriterion("POST not like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostIn(List<String> values) {
            addCriterion("POST in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotIn(List<String> values) {
            addCriterion("POST not in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostBetween(String value1, String value2) {
            addCriterion("POST between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotBetween(String value1, String value2) {
            addCriterion("POST not between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("ROLE is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("ROLE =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("ROLE <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("ROLE >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("ROLE <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("ROLE <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("ROLE like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("ROLE not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("ROLE in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("ROLE not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("ROLE between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("ROLE not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdIsNull() {
            addCriterion("FK_PP_ATTACHMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdIsNotNull() {
            addCriterion("FK_PP_ATTACHMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdEqualTo(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID =", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdNotEqualTo(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID <>", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdGreaterThan(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID >", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID >=", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdLessThan(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID <", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdLessThanOrEqualTo(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID <=", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdLike(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID like", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdNotLike(String value) {
            addCriterion("FK_PP_ATTACHMENT_ID not like", value, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdIn(List<String> values) {
            addCriterion("FK_PP_ATTACHMENT_ID in", values, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdNotIn(List<String> values) {
            addCriterion("FK_PP_ATTACHMENT_ID not in", values, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdBetween(String value1, String value2) {
            addCriterion("FK_PP_ATTACHMENT_ID between", value1, value2, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkPpAttachmentIdNotBetween(String value1, String value2) {
            addCriterion("FK_PP_ATTACHMENT_ID not between", value1, value2, "fkPpAttachmentId");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceIsNull() {
            addCriterion("EXPERT_EVIDENCE is null");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceIsNotNull() {
            addCriterion("EXPERT_EVIDENCE is not null");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceEqualTo(int value) {
            addCriterion("EXPERT_EVIDENCE =", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceNotEqualTo(int value) {
            addCriterion("EXPERT_EVIDENCE <>", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceGreaterThan(int value) {
            addCriterion("EXPERT_EVIDENCE >", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceGreaterThanOrEqualTo(int value) {
            addCriterion("EXPERT_EVIDENCE >=", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceLessThan(int value) {
            addCriterion("EXPERT_EVIDENCE <", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceLessThanOrEqualTo(int value) {
            addCriterion("EXPERT_EVIDENCE <=", value, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceIn(List<Integer> values) {
            addCriterion("EXPERT_EVIDENCE in", values, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceNotIn(List<Integer> values) {
            addCriterion("EXPERT_EVIDENCE not in", values, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceBetween(int value1, int value2) {
            addCriterion("EXPERT_EVIDENCE between", value1, value2, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andExpertEvidenceNotBetween(int value1, int value2) {
            addCriterion("EXPERT_EVIDENCE not between", value1, value2, "expertEvidence");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdIsNull() {
            addCriterion("FK_EE_ATTACHMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdIsNotNull() {
            addCriterion("FK_EE_ATTACHMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdEqualTo(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID =", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdNotEqualTo(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID <>", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdGreaterThan(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID >", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID >=", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdLessThan(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID <", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdLessThanOrEqualTo(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID <=", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdLike(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID like", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdNotLike(String value) {
            addCriterion("FK_EE_ATTACHMENT_ID not like", value, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdIn(List<String> values) {
            addCriterion("FK_EE_ATTACHMENT_ID in", values, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdNotIn(List<String> values) {
            addCriterion("FK_EE_ATTACHMENT_ID not in", values, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdBetween(String value1, String value2) {
            addCriterion("FK_EE_ATTACHMENT_ID between", value1, value2, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkEeAttachmentIdNotBetween(String value1, String value2) {
            addCriterion("FK_EE_ATTACHMENT_ID not between", value1, value2, "fkEeAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdIsNull() {
            addCriterion("FK_RP_PERMIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdIsNotNull() {
            addCriterion("FK_RP_PERMIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdEqualTo(String value) {
            addCriterion("FK_RP_PERMIT_ID =", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdNotEqualTo(String value) {
            addCriterion("FK_RP_PERMIT_ID <>", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdGreaterThan(String value) {
            addCriterion("FK_RP_PERMIT_ID >", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_RP_PERMIT_ID >=", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdLessThan(String value) {
            addCriterion("FK_RP_PERMIT_ID <", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdLessThanOrEqualTo(String value) {
            addCriterion("FK_RP_PERMIT_ID <=", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdLike(String value) {
            addCriterion("FK_RP_PERMIT_ID like", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdNotLike(String value) {
            addCriterion("FK_RP_PERMIT_ID not like", value, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdIn(List<String> values) {
            addCriterion("FK_RP_PERMIT_ID in", values, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdNotIn(List<String> values) {
            addCriterion("FK_RP_PERMIT_ID not in", values, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdBetween(String value1, String value2) {
            addCriterion("FK_RP_PERMIT_ID between", value1, value2, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkRpPermitIdNotBetween(String value1, String value2) {
            addCriterion("FK_RP_PERMIT_ID not between", value1, value2, "fkRpPermitId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdIsNull() {
            addCriterion("FK_INVITATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdIsNotNull() {
            addCriterion("FK_INVITATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdEqualTo(String value) {
            addCriterion("FK_INVITATION_ID =", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdNotEqualTo(String value) {
            addCriterion("FK_INVITATION_ID <>", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdGreaterThan(String value) {
            addCriterion("FK_INVITATION_ID >", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_INVITATION_ID >=", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdLessThan(String value) {
            addCriterion("FK_INVITATION_ID <", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdLessThanOrEqualTo(String value) {
            addCriterion("FK_INVITATION_ID <=", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdLike(String value) {
            addCriterion("FK_INVITATION_ID like", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdNotLike(String value) {
            addCriterion("FK_INVITATION_ID not like", value, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdIn(List<String> values) {
            addCriterion("FK_INVITATION_ID in", values, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdNotIn(List<String> values) {
            addCriterion("FK_INVITATION_ID not in", values, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdBetween(String value1, String value2) {
            addCriterion("FK_INVITATION_ID between", value1, value2, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andFkInvitationIdNotBetween(String value1, String value2) {
            addCriterion("FK_INVITATION_ID not between", value1, value2, "fkInvitationId");
            return (Criteria) this;
        }

        public Criteria andIsHereIsNull() {
            addCriterion("IS_HERE is null");
            return (Criteria) this;
        }

        public Criteria andIsHereIsNotNull() {
            addCriterion("IS_HERE is not null");
            return (Criteria) this;
        }

        public Criteria andIsHereEqualTo(int value) {
            addCriterion("IS_HERE =", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereNotEqualTo(int value) {
            addCriterion("IS_HERE <>", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereGreaterThan(int value) {
            addCriterion("IS_HERE >", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereGreaterThanOrEqualTo(int value) {
            addCriterion("IS_HERE >=", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereLessThan(int value) {
            addCriterion("IS_HERE <", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereLessThanOrEqualTo(int value) {
            addCriterion("IS_HERE <=", value, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereIn(List<Integer> values) {
            addCriterion("IS_HERE in", values, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereNotIn(List<Integer> values) {
            addCriterion("IS_HERE not in", values, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereBetween(int value1, int value2) {
            addCriterion("IS_HERE between", value1, value2, "isHere");
            return (Criteria) this;
        }

        public Criteria andIsHereNotBetween(int value1, int value2) {
            addCriterion("IS_HERE not between", value1, value2, "isHere");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(int value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(int value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(int value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(int value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(int value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(int value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(int value1, int value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(int value1, int value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("EDIT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("EDIT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("EDIT_DATE =", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("EDIT_DATE <>", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("EDIT_DATE >", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EDIT_DATE >=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("EDIT_DATE <", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("EDIT_DATE <=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateIn(List<Date> values) {
            addCriterion("EDIT_DATE in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotIn(List<Date> values) {
            addCriterion("EDIT_DATE not in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("EDIT_DATE between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("EDIT_DATE not between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andEditUserIsNull() {
            addCriterion("EDIT_USER is null");
            return (Criteria) this;
        }

        public Criteria andEditUserIsNotNull() {
            addCriterion("EDIT_USER is not null");
            return (Criteria) this;
        }

        public Criteria andEditUserEqualTo(String value) {
            addCriterion("EDIT_USER =", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotEqualTo(String value) {
            addCriterion("EDIT_USER <>", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserGreaterThan(String value) {
            addCriterion("EDIT_USER >", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserGreaterThanOrEqualTo(String value) {
            addCriterion("EDIT_USER >=", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLessThan(String value) {
            addCriterion("EDIT_USER <", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLessThanOrEqualTo(String value) {
            addCriterion("EDIT_USER <=", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLike(String value) {
            addCriterion("EDIT_USER like", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotLike(String value) {
            addCriterion("EDIT_USER not like", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserIn(List<String> values) {
            addCriterion("EDIT_USER in", values, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotIn(List<String> values) {
            addCriterion("EDIT_USER not in", values, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserBetween(String value1, String value2) {
            addCriterion("EDIT_USER between", value1, value2, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotBetween(String value1, String value2) {
            addCriterion("EDIT_USER not between", value1, value2, "editUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 10:12:12 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_FOREIGNER
     *
     * @mbggenerated Mon Sep 23 10:12:12 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}