package cn.com.jnpc.foreign.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FiResidencePermitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public FiResidencePermitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(int value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(int value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(int value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(int value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(int value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(int value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(int value1, int value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(int value1, int value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdIsNull() {
            addCriterion("RESIDENCE_PERMIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdIsNotNull() {
            addCriterion("RESIDENCE_PERMIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_ID =", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdNotEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_ID <>", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdGreaterThan(String value) {
            addCriterion("RESIDENCE_PERMIT_ID >", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdGreaterThanOrEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_ID >=", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdLessThan(String value) {
            addCriterion("RESIDENCE_PERMIT_ID <", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdLessThanOrEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_ID <=", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdLike(String value) {
            addCriterion("RESIDENCE_PERMIT_ID like", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdNotLike(String value) {
            addCriterion("RESIDENCE_PERMIT_ID not like", value, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdIn(List<String> values) {
            addCriterion("RESIDENCE_PERMIT_ID in", values, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdNotIn(List<String> values) {
            addCriterion("RESIDENCE_PERMIT_ID not in", values, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdBetween(String value1, String value2) {
            addCriterion("RESIDENCE_PERMIT_ID between", value1, value2, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitIdNotBetween(String value1, String value2) {
            addCriterion("RESIDENCE_PERMIT_ID not between", value1, value2, "residencePermitId");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindIsNull() {
            addCriterion("RESIDENCE_PERMIT_KIND is null");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindIsNotNull() {
            addCriterion("RESIDENCE_PERMIT_KIND is not null");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND =", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindNotEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND <>", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindGreaterThan(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND >", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindGreaterThanOrEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND >=", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindLessThan(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND <", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindLessThanOrEqualTo(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND <=", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindLike(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND like", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindNotLike(String value) {
            addCriterion("RESIDENCE_PERMIT_KIND not like", value, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindIn(List<String> values) {
            addCriterion("RESIDENCE_PERMIT_KIND in", values, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindNotIn(List<String> values) {
            addCriterion("RESIDENCE_PERMIT_KIND not in", values, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindBetween(String value1, String value2) {
            addCriterion("RESIDENCE_PERMIT_KIND between", value1, value2, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andResidencePermitKindNotBetween(String value1, String value2) {
            addCriterion("RESIDENCE_PERMIT_KIND not between", value1, value2, "residencePermitKind");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateIsNull() {
            addCriterion("RP_EXP_ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateIsNotNull() {
            addCriterion("RP_EXP_ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateEqualTo(Date value) {
            addCriterion("RP_EXP_ENDDATE =", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateNotEqualTo(Date value) {
            addCriterion("RP_EXP_ENDDATE <>", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateGreaterThan(Date value) {
            addCriterion("RP_EXP_ENDDATE >", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("RP_EXP_ENDDATE >=", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateLessThan(Date value) {
            addCriterion("RP_EXP_ENDDATE <", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateLessThanOrEqualTo(Date value) {
            addCriterion("RP_EXP_ENDDATE <=", value, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateIn(List<Date> values) {
            addCriterion("RP_EXP_ENDDATE in", values, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateNotIn(List<Date> values) {
            addCriterion("RP_EXP_ENDDATE not in", values, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateBetween(Date value1, Date value2) {
            addCriterion("RP_EXP_ENDDATE between", value1, value2, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpExpEnddateNotBetween(Date value1, Date value2) {
            addCriterion("RP_EXP_ENDDATE not between", value1, value2, "rpExpEnddate");
            return (Criteria) this;
        }

        public Criteria andRpAddressIsNull() {
            addCriterion("RP_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andRpAddressIsNotNull() {
            addCriterion("RP_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andRpAddressEqualTo(String value) {
            addCriterion("RP_ADDRESS =", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressNotEqualTo(String value) {
            addCriterion("RP_ADDRESS <>", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressGreaterThan(String value) {
            addCriterion("RP_ADDRESS >", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("RP_ADDRESS >=", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressLessThan(String value) {
            addCriterion("RP_ADDRESS <", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressLessThanOrEqualTo(String value) {
            addCriterion("RP_ADDRESS <=", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressLike(String value) {
            addCriterion("RP_ADDRESS like", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressNotLike(String value) {
            addCriterion("RP_ADDRESS not like", value, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressIn(List<String> values) {
            addCriterion("RP_ADDRESS in", values, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressNotIn(List<String> values) {
            addCriterion("RP_ADDRESS not in", values, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressBetween(String value1, String value2) {
            addCriterion("RP_ADDRESS between", value1, value2, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andRpAddressNotBetween(String value1, String value2) {
            addCriterion("RP_ADDRESS not between", value1, value2, "rpAddress");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdIsNull() {
            addCriterion("FK_ATTACHMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdIsNotNull() {
            addCriterion("FK_ATTACHMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdEqualTo(String value) {
            addCriterion("FK_ATTACHMENT_ID =", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdNotEqualTo(String value) {
            addCriterion("FK_ATTACHMENT_ID <>", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdGreaterThan(String value) {
            addCriterion("FK_ATTACHMENT_ID >", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_ATTACHMENT_ID >=", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdLessThan(String value) {
            addCriterion("FK_ATTACHMENT_ID <", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdLessThanOrEqualTo(String value) {
            addCriterion("FK_ATTACHMENT_ID <=", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdLike(String value) {
            addCriterion("FK_ATTACHMENT_ID like", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdNotLike(String value) {
            addCriterion("FK_ATTACHMENT_ID not like", value, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdIn(List<String> values) {
            addCriterion("FK_ATTACHMENT_ID in", values, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdNotIn(List<String> values) {
            addCriterion("FK_ATTACHMENT_ID not in", values, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdBetween(String value1, String value2) {
            addCriterion("FK_ATTACHMENT_ID between", value1, value2, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkAttachmentIdNotBetween(String value1, String value2) {
            addCriterion("FK_ATTACHMENT_ID not between", value1, value2, "fkAttachmentId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdIsNull() {
            addCriterion("FK_FOREIGNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdIsNotNull() {
            addCriterion("FK_FOREIGNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdEqualTo(String value) {
            addCriterion("FK_FOREIGNER_ID =", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdNotEqualTo(String value) {
            addCriterion("FK_FOREIGNER_ID <>", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdGreaterThan(String value) {
            addCriterion("FK_FOREIGNER_ID >", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_FOREIGNER_ID >=", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdLessThan(String value) {
            addCriterion("FK_FOREIGNER_ID <", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdLessThanOrEqualTo(String value) {
            addCriterion("FK_FOREIGNER_ID <=", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdLike(String value) {
            addCriterion("FK_FOREIGNER_ID like", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdNotLike(String value) {
            addCriterion("FK_FOREIGNER_ID not like", value, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdIn(List<String> values) {
            addCriterion("FK_FOREIGNER_ID in", values, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdNotIn(List<String> values) {
            addCriterion("FK_FOREIGNER_ID not in", values, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdBetween(String value1, String value2) {
            addCriterion("FK_FOREIGNER_ID between", value1, value2, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andFkForeignerIdNotBetween(String value1, String value2) {
            addCriterion("FK_FOREIGNER_ID not between", value1, value2, "fkForeignerId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(int value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(int value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(int value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(int value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(int value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(int value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(int value1, int value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(int value1, int value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("EDIT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("EDIT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("EDIT_DATE =", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("EDIT_DATE <>", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("EDIT_DATE >", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EDIT_DATE >=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("EDIT_DATE <", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("EDIT_DATE <=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateIn(List<Date> values) {
            addCriterion("EDIT_DATE in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotIn(List<Date> values) {
            addCriterion("EDIT_DATE not in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("EDIT_DATE between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("EDIT_DATE not between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditUserIsNull() {
            addCriterion("EDIT_USER is null");
            return (Criteria) this;
        }

        public Criteria andEditUserIsNotNull() {
            addCriterion("EDIT_USER is not null");
            return (Criteria) this;
        }

        public Criteria andEditUserEqualTo(String value) {
            addCriterion("EDIT_USER =", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotEqualTo(String value) {
            addCriterion("EDIT_USER <>", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserGreaterThan(String value) {
            addCriterion("EDIT_USER >", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserGreaterThanOrEqualTo(String value) {
            addCriterion("EDIT_USER >=", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLessThan(String value) {
            addCriterion("EDIT_USER <", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLessThanOrEqualTo(String value) {
            addCriterion("EDIT_USER <=", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserLike(String value) {
            addCriterion("EDIT_USER like", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotLike(String value) {
            addCriterion("EDIT_USER not like", value, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserIn(List<String> values) {
            addCriterion("EDIT_USER in", values, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotIn(List<String> values) {
            addCriterion("EDIT_USER not in", values, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserBetween(String value1, String value2) {
            addCriterion("EDIT_USER between", value1, value2, "editUser");
            return (Criteria) this;
        }

        public Criteria andEditUserNotBetween(String value1, String value2) {
            addCriterion("EDIT_USER not between", value1, value2, "editUser");
            return (Criteria) this;
        }

        public Criteria andIsDeferIsNull() {
            addCriterion("IS_DEFER is null");
            return (Criteria) this;
        }

        public Criteria andIsDeferIsNotNull() {
            addCriterion("IS_DEFER is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeferEqualTo(int value) {
            addCriterion("IS_DEFER =", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferNotEqualTo(int value) {
            addCriterion("IS_DEFER <>", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferGreaterThan(int value) {
            addCriterion("IS_DEFER >", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferGreaterThanOrEqualTo(int value) {
            addCriterion("IS_DEFER >=", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferLessThan(int value) {
            addCriterion("IS_DEFER <", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferLessThanOrEqualTo(int value) {
            addCriterion("IS_DEFER <=", value, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferIn(List<Integer> values) {
            addCriterion("IS_DEFER in", values, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferNotIn(List<Integer> values) {
            addCriterion("IS_DEFER not in", values, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferBetween(int value1, int value2) {
            addCriterion("IS_DEFER between", value1, value2, "isDefer");
            return (Criteria) this;
        }

        public Criteria andIsDeferNotBetween(int value1, int value2) {
            addCriterion("IS_DEFER not between", value1, value2, "isDefer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 10:12:13 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}