package cn.com.jnpc.foreign.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.com.jnpc.foreign.mapperprovider.FiBlobSqlProvider;
import cn.com.jnpc.foreign.model.FiBlobExample;
import cn.com.jnpc.foreign.po.FiBlob;
import cn.com.jnpc.foreign.po.FiForeigner;
import cn.com.jnpc.foreign.vo.PageMybatis;

public interface FiBlobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @SelectProvider(type=FiBlobSqlProvider.class, method="countByExample")
    int countByExample(FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @DeleteProvider(type=FiBlobSqlProvider.class, method="deleteByExample")
    int deleteByExample(FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @Delete({
        "delete from FI_BLOB",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @Insert({
        "insert into FI_BLOB (ID,PARENT_ID, ",
        "FILE_V)",
        "values (#{id,jdbcType=NUMERIC},#{parentId,jdbcType=VARCHAR}, ",
        "#{fileV,jdbcType=BLOB})"
    })
    @SelectKey(before=true,keyProperty="id",resultType=Integer.class,statement="select fiblob_sequence.nextval as id from dual")
    int insert(FiBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @InsertProvider(type=FiBlobSqlProvider.class, method="insertSelective")
    int insertSelective(FiBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @SelectProvider(type=FiBlobSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_V", property="fileV", jdbcType=JdbcType.BLOB)
    })
    List<FiBlob> selectByExampleWithBLOBs(FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @SelectProvider(type=FiBlobSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR)
    })
    List<FiBlob> selectByExample(FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @Select({
        "select",
        "ID, PARENT_ID, FILE_V",
        "from FI_BLOB",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_V", property="fileV", jdbcType=JdbcType.BLOB)
    })
    FiBlob selectByPrimaryKey(int id);
    
    @SelectProvider(type=FiBlobSqlProvider.class, method="selectByPage")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_V", property="fileV", jdbcType=JdbcType.BLOB)
    })
    List<FiBlob> selectByPage(PageMybatis page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @UpdateProvider(type=FiBlobSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FiBlob record, @Param("example") FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @UpdateProvider(type=FiBlobSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") FiBlob record, @Param("example") FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @UpdateProvider(type=FiBlobSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FiBlob record, @Param("example") FiBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @UpdateProvider(type=FiBlobSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FiBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @Update({
        "update FI_BLOB",
        "set PARENT_ID = #{parentId,jdbcType=VARCHAR},",
          "FILE_V = #{fileV,jdbcType=BLOB}",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKeyWithBLOBs(FiBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_BLOB
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    @Update({
        "update FI_BLOB",
        "set PARENT_ID = #{parentId,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(FiBlob record);
}