package cn.com.jnpc.foreign.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.com.jnpc.foreign.mapperprovider.FiResidencePermitSqlProvider;
import cn.com.jnpc.foreign.model.FiResidencePermitExample;
import cn.com.jnpc.foreign.po.FiResidencePermit;

public interface FiResidencePermitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @SelectProvider(type=FiResidencePermitSqlProvider.class, method="countByExample")
    int countByExample(FiResidencePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @DeleteProvider(type=FiResidencePermitSqlProvider.class, method="deleteByExample")
    int deleteByExample(FiResidencePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @Delete({
        "delete from FI_RESIDENCE_PERMIT",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @Insert({
        "insert into FI_RESIDENCE_PERMIT (ID, RESIDENCE_PERMIT_ID, ",
        "RESIDENCE_PERMIT_KIND, RP_EXP_ENDDATE, ",
        "RP_ADDRESS, FK_ATTACHMENT_ID, ",
        "FK_FOREIGNER_ID, STATUS, ",
        "CREATE_DATE, CREATE_USER, ",
        "EDIT_DATE, EDIT_USER, ",
        "IS_DEFER)",
        "values (#{id,jdbcType=NUMERIC}, #{residencePermitId,jdbcType=VARCHAR}, ",
        "#{residencePermitKind,jdbcType=VARCHAR}, #{rpExpEnddate,jdbcType=TIMESTAMP}, ",
        "#{rpAddress,jdbcType=VARCHAR}, #{fkAttachmentId,jdbcType=VARCHAR}, ",
        "#{fkForeignerId,jdbcType=VARCHAR}, #{status,jdbcType=NUMERIC}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{editDate,jdbcType=TIMESTAMP}, #{editUser,jdbcType=VARCHAR}, ",
        "#{isDefer,jdbcType=NUMERIC})"
    })
    @SelectKey(before=true,keyProperty="id",resultType=Integer.class,statement="select firesidencepermit_sequence.nextval as id from dual")
    int insert(FiResidencePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @InsertProvider(type=FiResidencePermitSqlProvider.class, method="insertSelective")
    int insertSelective(FiResidencePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @SelectProvider(type=FiResidencePermitSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="RESIDENCE_PERMIT_ID", property="residencePermitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESIDENCE_PERMIT_KIND", property="residencePermitKind", jdbcType=JdbcType.VARCHAR),
        @Result(column="RP_EXP_ENDDATE", property="rpExpEnddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RP_ADDRESS", property="rpAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="FK_ATTACHMENT_ID", property="fkAttachmentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FK_FOREIGNER_ID", property="fkForeignerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.NUMERIC),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_USER", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDIT_DATE", property="editDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EDIT_USER", property="editUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_DEFER", property="isDefer", jdbcType=JdbcType.NUMERIC)
    })
    List<FiResidencePermit> selectByExample(FiResidencePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @Select({
        "select",
        "ID, RESIDENCE_PERMIT_ID, RESIDENCE_PERMIT_KIND, RP_EXP_ENDDATE, RP_ADDRESS, ",
        "FK_ATTACHMENT_ID, FK_FOREIGNER_ID, STATUS, CREATE_DATE, CREATE_USER, EDIT_DATE, ",
        "EDIT_USER, IS_DEFER",
        "from FI_RESIDENCE_PERMIT",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="RESIDENCE_PERMIT_ID", property="residencePermitId", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESIDENCE_PERMIT_KIND", property="residencePermitKind", jdbcType=JdbcType.VARCHAR),
        @Result(column="RP_EXP_ENDDATE", property="rpExpEnddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RP_ADDRESS", property="rpAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="FK_ATTACHMENT_ID", property="fkAttachmentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FK_FOREIGNER_ID", property="fkForeignerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.NUMERIC),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_USER", property="createUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDIT_DATE", property="editDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EDIT_USER", property="editUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_DEFER", property="isDefer", jdbcType=JdbcType.NUMERIC)
    })
    FiResidencePermit selectByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @UpdateProvider(type=FiResidencePermitSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FiResidencePermit record, @Param("example") FiResidencePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @UpdateProvider(type=FiResidencePermitSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FiResidencePermit record, @Param("example") FiResidencePermitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @UpdateProvider(type=FiResidencePermitSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FiResidencePermit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    @Update({
        "update FI_RESIDENCE_PERMIT",
        "set RESIDENCE_PERMIT_ID = #{residencePermitId,jdbcType=VARCHAR},",
          "RESIDENCE_PERMIT_KIND = #{residencePermitKind,jdbcType=VARCHAR},",
          "RP_EXP_ENDDATE = #{rpExpEnddate,jdbcType=TIMESTAMP},",
          "RP_ADDRESS = #{rpAddress,jdbcType=VARCHAR},",
          "FK_ATTACHMENT_ID = #{fkAttachmentId,jdbcType=VARCHAR},",
          "FK_FOREIGNER_ID = #{fkForeignerId,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=NUMERIC},",
          "CREATE_DATE = #{createDate,jdbcType=TIMESTAMP},",
          "CREATE_USER = #{createUser,jdbcType=VARCHAR},",
          "EDIT_DATE = #{editDate,jdbcType=TIMESTAMP},",
          "EDIT_USER = #{editUser,jdbcType=VARCHAR},",
          "IS_DEFER = #{isDefer,jdbcType=NUMERIC}",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(FiResidencePermit record);
}