package cn.com.jnpc.foreign.mapperprovider;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import cn.com.jnpc.foreign.model.FiMiddleExample;
import cn.com.jnpc.foreign.model.FiMiddleExample.Criteria;
import cn.com.jnpc.foreign.model.FiMiddleExample.Criterion;
import cn.com.jnpc.foreign.po.FiMiddle;

public class FiMiddleSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String countByExample(FiMiddleExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("FI_MIDDLE");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String deleteByExample(FiMiddleExample example) {
        BEGIN();
        DELETE_FROM("FI_MIDDLE");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String insertSelective(FiMiddle record) {
        BEGIN();
        INSERT_INTO("FI_MIDDLE");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=DECIMAL}");
        }
        
        if (record.getFkInvitationId() != null) {
            VALUES("FK_INVITATION_ID", "#{fkInvitationId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonId() != null) {
            VALUES("FK_PERSON_ID", "#{fkPersonId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonPpid() != null) {
            VALUES("FK_PERSON_PPID", "#{fkPersonPpid,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("CREATE_DATE", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            VALUES("CREATE_USER", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditUser() != null) {
            VALUES("EDIT_USER", "#{editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            VALUES("EDIT_DATE", "#{editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWork() != null) {
            VALUES("WORK", "#{work,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkAddress() != null) {
            VALUES("WORK_ADDRESS", "#{workAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLivingAddress() != null) {
            VALUES("LIVING_ADDRESS", "#{livingAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeferId() != null) {
            VALUES("DEFER_ID", "#{deferId,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String selectByExample(FiMiddleExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ID");
        } else {
            SELECT("ID");
        }
        SELECT("FK_INVITATION_ID");
        SELECT("FK_PERSON_ID");
        SELECT("FK_PERSON_PPID");
        SELECT("CREATE_DATE");
        SELECT("CREATE_USER");
        SELECT("EDIT_USER");
        SELECT("EDIT_DATE");
        SELECT("WORK");
        SELECT("WORK_ADDRESS");
        SELECT("LIVING_ADDRESS");
        SELECT("DEFER_ID");
        FROM("FI_MIDDLE");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        FiMiddle record = (FiMiddle) parameter.get("record");
        FiMiddleExample example = (FiMiddleExample) parameter.get("example");
        
        BEGIN();
        UPDATE("FI_MIDDLE");
        
        if (record.getId() != null) {
            SET("ID = #{record.id,jdbcType=DECIMAL}");
        }
        
        if (record.getFkInvitationId() != null) {
            SET("FK_INVITATION_ID = #{record.fkInvitationId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonId() != null) {
            SET("FK_PERSON_ID = #{record.fkPersonId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonPpid() != null) {
            SET("FK_PERSON_PPID = #{record.fkPersonPpid,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("CREATE_DATE = #{record.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            SET("CREATE_USER = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditUser() != null) {
            SET("EDIT_USER = #{record.editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            SET("EDIT_DATE = #{record.editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWork() != null) {
            SET("WORK = #{record.work,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkAddress() != null) {
            SET("WORK_ADDRESS = #{record.workAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLivingAddress() != null) {
            SET("LIVING_ADDRESS = #{record.livingAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeferId() != null) {
            SET("DEFER_ID = #{record.deferId,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("FI_MIDDLE");
        
        SET("ID = #{record.id,jdbcType=DECIMAL}");
        SET("FK_INVITATION_ID = #{record.fkInvitationId,jdbcType=VARCHAR}");
        SET("FK_PERSON_ID = #{record.fkPersonId,jdbcType=VARCHAR}");
        SET("FK_PERSON_PPID = #{record.fkPersonPpid,jdbcType=VARCHAR}");
        SET("CREATE_DATE = #{record.createDate,jdbcType=TIMESTAMP}");
        SET("CREATE_USER = #{record.createUser,jdbcType=VARCHAR}");
        SET("EDIT_USER = #{record.editUser,jdbcType=VARCHAR}");
        SET("EDIT_DATE = #{record.editDate,jdbcType=TIMESTAMP}");
        SET("WORK = #{record.work,jdbcType=VARCHAR}");
        SET("WORK_ADDRESS = #{record.workAddress,jdbcType=VARCHAR}");
        SET("LIVING_ADDRESS = #{record.livingAddress,jdbcType=VARCHAR}");
        SET("DEFER_ID = #{record.deferId,jdbcType=VARCHAR}");
        
        FiMiddleExample example = (FiMiddleExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String updateByPrimaryKeySelective(FiMiddle record) {
        BEGIN();
        UPDATE("FI_MIDDLE");
        
        if (record.getFkInvitationId() != null) {
            SET("FK_INVITATION_ID = #{fkInvitationId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonId() != null) {
            SET("FK_PERSON_ID = #{fkPersonId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkPersonPpid() != null) {
            SET("FK_PERSON_PPID = #{fkPersonPpid,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            SET("CREATE_USER = #{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditUser() != null) {
            SET("EDIT_USER = #{editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            SET("EDIT_DATE = #{editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWork() != null) {
            SET("WORK = #{work,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkAddress() != null) {
            SET("WORK_ADDRESS = #{workAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLivingAddress() != null) {
            SET("LIVING_ADDRESS = #{livingAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeferId() != null) {
            SET("DEFER_ID = #{deferId,jdbcType=VARCHAR}");
        }
        
        WHERE("ID = #{id,jdbcType=DECIMAL}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_MIDDLE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    protected void applyWhere(FiMiddleExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}