package cn.com.jnpc.foreign.mapperprovider;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import cn.com.jnpc.foreign.model.FiResidencePermitExample;
import cn.com.jnpc.foreign.model.FiResidencePermitExample.Criteria;
import cn.com.jnpc.foreign.model.FiResidencePermitExample.Criterion;
import cn.com.jnpc.foreign.po.FiResidencePermit;

public class FiResidencePermitSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String countByExample(FiResidencePermitExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("FI_RESIDENCE_PERMIT");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String deleteByExample(FiResidencePermitExample example) {
        BEGIN();
        DELETE_FROM("FI_RESIDENCE_PERMIT");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String insertSelective(FiResidencePermit record) {
        BEGIN();
        INSERT_INTO("FI_RESIDENCE_PERMIT");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=DECIMAL}");
        }
        
        if (record.getResidencePermitId() != null) {
            VALUES("RESIDENCE_PERMIT_ID", "#{residencePermitId,jdbcType=VARCHAR}");
        }
        
        if (record.getResidencePermitKind() != null) {
            VALUES("RESIDENCE_PERMIT_KIND", "#{residencePermitKind,jdbcType=VARCHAR}");
        }
        
        if (record.getRpExpEnddate() != null) {
            VALUES("RP_EXP_ENDDATE", "#{rpExpEnddate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRpAddress() != null) {
            VALUES("RP_ADDRESS", "#{rpAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getFkAttachmentId() != null) {
            VALUES("FK_ATTACHMENT_ID", "#{fkAttachmentId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkForeignerId() != null) {
            VALUES("FK_FOREIGNER_ID", "#{fkForeignerId,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("CREATE_DATE", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            VALUES("CREATE_USER", "#{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            VALUES("EDIT_DATE", "#{editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEditUser() != null) {
            VALUES("EDIT_USER", "#{editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefer() != null) {
            VALUES("IS_DEFER", "#{isDefer,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String selectByExample(FiResidencePermitExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ID");
        } else {
            SELECT("ID");
        }
        SELECT("RESIDENCE_PERMIT_ID");
        SELECT("RESIDENCE_PERMIT_KIND");
        SELECT("RP_EXP_ENDDATE");
        SELECT("RP_ADDRESS");
        SELECT("FK_ATTACHMENT_ID");
        SELECT("FK_FOREIGNER_ID");
        SELECT("STATUS");
        SELECT("CREATE_DATE");
        SELECT("CREATE_USER");
        SELECT("EDIT_DATE");
        SELECT("EDIT_USER");
        SELECT("IS_DEFER");
        FROM("FI_RESIDENCE_PERMIT");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        FiResidencePermit record = (FiResidencePermit) parameter.get("record");
        FiResidencePermitExample example = (FiResidencePermitExample) parameter.get("example");
        
        BEGIN();
        UPDATE("FI_RESIDENCE_PERMIT");
        
        if (record.getId() != null) {
            SET("ID = #{record.id,jdbcType=DECIMAL}");
        }
        
        if (record.getResidencePermitId() != null) {
            SET("RESIDENCE_PERMIT_ID = #{record.residencePermitId,jdbcType=VARCHAR}");
        }
        
        if (record.getResidencePermitKind() != null) {
            SET("RESIDENCE_PERMIT_KIND = #{record.residencePermitKind,jdbcType=VARCHAR}");
        }
        
        if (record.getRpExpEnddate() != null) {
            SET("RP_EXP_ENDDATE = #{record.rpExpEnddate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRpAddress() != null) {
            SET("RP_ADDRESS = #{record.rpAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getFkAttachmentId() != null) {
            SET("FK_ATTACHMENT_ID = #{record.fkAttachmentId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkForeignerId() != null) {
            SET("FK_FOREIGNER_ID = #{record.fkForeignerId,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateDate() != null) {
            SET("CREATE_DATE = #{record.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            SET("CREATE_USER = #{record.createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            SET("EDIT_DATE = #{record.editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEditUser() != null) {
            SET("EDIT_USER = #{record.editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefer() != null) {
            SET("IS_DEFER = #{record.isDefer,jdbcType=DECIMAL}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("FI_RESIDENCE_PERMIT");
        
        SET("ID = #{record.id,jdbcType=DECIMAL}");
        SET("RESIDENCE_PERMIT_ID = #{record.residencePermitId,jdbcType=VARCHAR}");
        SET("RESIDENCE_PERMIT_KIND = #{record.residencePermitKind,jdbcType=VARCHAR}");
        SET("RP_EXP_ENDDATE = #{record.rpExpEnddate,jdbcType=TIMESTAMP}");
        SET("RP_ADDRESS = #{record.rpAddress,jdbcType=VARCHAR}");
        SET("FK_ATTACHMENT_ID = #{record.fkAttachmentId,jdbcType=VARCHAR}");
        SET("FK_FOREIGNER_ID = #{record.fkForeignerId,jdbcType=VARCHAR}");
        SET("STATUS = #{record.status,jdbcType=DECIMAL}");
        SET("CREATE_DATE = #{record.createDate,jdbcType=TIMESTAMP}");
        SET("CREATE_USER = #{record.createUser,jdbcType=VARCHAR}");
        SET("EDIT_DATE = #{record.editDate,jdbcType=TIMESTAMP}");
        SET("EDIT_USER = #{record.editUser,jdbcType=VARCHAR}");
        SET("IS_DEFER = #{record.isDefer,jdbcType=DECIMAL}");
        
        FiResidencePermitExample example = (FiResidencePermitExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:13 CST 2013
     */
    public String updateByPrimaryKeySelective(FiResidencePermit record) {
        BEGIN();
        UPDATE("FI_RESIDENCE_PERMIT");
        
        if (record.getResidencePermitId() != null) {
            SET("RESIDENCE_PERMIT_ID = #{residencePermitId,jdbcType=VARCHAR}");
        }
        
        if (record.getResidencePermitKind() != null) {
            SET("RESIDENCE_PERMIT_KIND = #{residencePermitKind,jdbcType=VARCHAR}");
        }
        
        if (record.getRpExpEnddate() != null) {
            SET("RP_EXP_ENDDATE = #{rpExpEnddate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRpAddress() != null) {
            SET("RP_ADDRESS = #{rpAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getFkAttachmentId() != null) {
            SET("FK_ATTACHMENT_ID = #{fkAttachmentId,jdbcType=VARCHAR}");
        }
        
        if (record.getFkForeignerId() != null) {
            SET("FK_FOREIGNER_ID = #{fkForeignerId,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateDate() != null) {
            SET("CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            SET("CREATE_USER = #{createUser,jdbcType=VARCHAR}");
        }
        
        if (record.getEditDate() != null) {
            SET("EDIT_DATE = #{editDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEditUser() != null) {
            SET("EDIT_USER = #{editUser,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefer() != null) {
            SET("IS_DEFER = #{isDefer,jdbcType=DECIMAL}");
        }
        
        WHERE("ID = #{id,jdbcType=DECIMAL}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_RESIDENCE_PERMIT
     *
     * @mbggenerated Mon Sep 23 10:12:14 CST 2013
     */
    protected void applyWhere(FiResidencePermitExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}