package cn.com.jnpc.foreign.po;

import java.util.Date;

public class FiAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.OLD_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String oldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.STORE_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.URL
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.FILE_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.KF_PARENT_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String kfParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.PARENT_TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String parentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.STATUS
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.START_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.END_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.CARD_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.EDIT_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.CREATE_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.EDIT_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private String editUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_ATTACHMENT.IS_DEFER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    private Integer isDefer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.ID
     *
     * @return the value of FI_ATTACHMENT.ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.ID
     *
     * @param id the value for FI_ATTACHMENT.ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.OLD_NAME
     *
     * @return the value of FI_ATTACHMENT.OLD_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.OLD_NAME
     *
     * @param oldName the value for FI_ATTACHMENT.OLD_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setOldName(String oldName) {
        this.oldName = oldName == null ? null : oldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.STORE_NAME
     *
     * @return the value of FI_ATTACHMENT.STORE_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.STORE_NAME
     *
     * @param storeName the value for FI_ATTACHMENT.STORE_NAME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.URL
     *
     * @return the value of FI_ATTACHMENT.URL
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.URL
     *
     * @param url the value for FI_ATTACHMENT.URL
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.FILE_ID
     *
     * @return the value of FI_ATTACHMENT.FILE_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.FILE_ID
     *
     * @param fileId the value for FI_ATTACHMENT.FILE_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.TYPE
     *
     * @return the value of FI_ATTACHMENT.TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.TYPE
     *
     * @param type the value for FI_ATTACHMENT.TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.KF_PARENT_ID
     *
     * @return the value of FI_ATTACHMENT.KF_PARENT_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getKfParentId() {
        return kfParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.KF_PARENT_ID
     *
     * @param kfParentId the value for FI_ATTACHMENT.KF_PARENT_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setKfParentId(String kfParentId) {
        this.kfParentId = kfParentId == null ? null : kfParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.PARENT_TYPE
     *
     * @return the value of FI_ATTACHMENT.PARENT_TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.PARENT_TYPE
     *
     * @param parentType the value for FI_ATTACHMENT.PARENT_TYPE
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setParentType(String parentType) {
        this.parentType = parentType == null ? null : parentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.STATUS
     *
     * @return the value of FI_ATTACHMENT.STATUS
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.STATUS
     *
     * @param status the value for FI_ATTACHMENT.STATUS
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.START_TIME
     *
     * @return the value of FI_ATTACHMENT.START_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.START_TIME
     *
     * @param startTime the value for FI_ATTACHMENT.START_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.END_TIME
     *
     * @return the value of FI_ATTACHMENT.END_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.END_TIME
     *
     * @param endTime the value for FI_ATTACHMENT.END_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.CARD_ID
     *
     * @return the value of FI_ATTACHMENT.CARD_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.CARD_ID
     *
     * @param cardId the value for FI_ATTACHMENT.CARD_ID
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.CREATE_TIME
     *
     * @return the value of FI_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.CREATE_TIME
     *
     * @param createTime the value for FI_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.EDIT_TIME
     *
     * @return the value of FI_ATTACHMENT.EDIT_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.EDIT_TIME
     *
     * @param editTime the value for FI_ATTACHMENT.EDIT_TIME
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.CREATE_USER
     *
     * @return the value of FI_ATTACHMENT.CREATE_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.CREATE_USER
     *
     * @param createUser the value for FI_ATTACHMENT.CREATE_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.EDIT_USER
     *
     * @return the value of FI_ATTACHMENT.EDIT_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.EDIT_USER
     *
     * @param editUser the value for FI_ATTACHMENT.EDIT_USER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser == null ? null : editUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_ATTACHMENT.IS_DEFER
     *
     * @return the value of FI_ATTACHMENT.IS_DEFER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public Integer getIsDefer() {
        return isDefer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_ATTACHMENT.IS_DEFER
     *
     * @param isDefer the value for FI_ATTACHMENT.IS_DEFER
     *
     * @mbggenerated Mon Sep 23 01:08:51 CST 2013
     */
    public void setIsDefer(Integer isDefer) {
        this.isDefer = isDefer;
    }
}