package cn.com.jnpc.foreign.po;

import java.util.Date;

public class FiForeigner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.NAME
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.SEX
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.BIRTHDAY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.COUNTRY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.COMPANY_DEPARTMENT
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String companyDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.PASSPORT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.PASSPORT_EXP_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Date passportExpDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.POST
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.ROLE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.FK_PP_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String fkPpAttachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.EXPERT_EVIDENCE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer expertEvidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.FK_EE_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String fkEeAttachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.FK_RP_PERMIT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String fkRpPermitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.FK_INVITATION_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String fkInvitationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.FK_BEUSE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer fkBeuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.IS_HERE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer isHere;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.STATUS
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.CREATE_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.EDIT_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.CREATE_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_FOREIGNER.EDIT_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    private String editUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.ID
     *
     * @return the value of FI_FOREIGNER.ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.ID
     *
     * @param id the value for FI_FOREIGNER.ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.NAME
     *
     * @return the value of FI_FOREIGNER.NAME
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.NAME
     *
     * @param name the value for FI_FOREIGNER.NAME
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.SEX
     *
     * @return the value of FI_FOREIGNER.SEX
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.SEX
     *
     * @param sex the value for FI_FOREIGNER.SEX
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.BIRTHDAY
     *
     * @return the value of FI_FOREIGNER.BIRTHDAY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.BIRTHDAY
     *
     * @param birthday the value for FI_FOREIGNER.BIRTHDAY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.COUNTRY
     *
     * @return the value of FI_FOREIGNER.COUNTRY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.COUNTRY
     *
     * @param country the value for FI_FOREIGNER.COUNTRY
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.COMPANY_DEPARTMENT
     *
     * @return the value of FI_FOREIGNER.COMPANY_DEPARTMENT
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getCompanyDepartment() {
        return companyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.COMPANY_DEPARTMENT
     *
     * @param companyDepartment the value for FI_FOREIGNER.COMPANY_DEPARTMENT
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setCompanyDepartment(String companyDepartment) {
        this.companyDepartment = companyDepartment == null ? null : companyDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.PASSPORT_ID
     *
     * @return the value of FI_FOREIGNER.PASSPORT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.PASSPORT_ID
     *
     * @param passportId the value for FI_FOREIGNER.PASSPORT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setPassportId(String passportId) {
        this.passportId = passportId == null ? null : passportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.PASSPORT_EXP_DATE
     *
     * @return the value of FI_FOREIGNER.PASSPORT_EXP_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Date getPassportExpDate() {
        return passportExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.PASSPORT_EXP_DATE
     *
     * @param passportExpDate the value for FI_FOREIGNER.PASSPORT_EXP_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setPassportExpDate(Date passportExpDate) {
        this.passportExpDate = passportExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.POST
     *
     * @return the value of FI_FOREIGNER.POST
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.POST
     *
     * @param post the value for FI_FOREIGNER.POST
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.ROLE
     *
     * @return the value of FI_FOREIGNER.ROLE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.ROLE
     *
     * @param role the value for FI_FOREIGNER.ROLE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.FK_PP_ATTACHMENT_ID
     *
     * @return the value of FI_FOREIGNER.FK_PP_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getFkPpAttachmentId() {
        return fkPpAttachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.FK_PP_ATTACHMENT_ID
     *
     * @param fkPpAttachmentId the value for FI_FOREIGNER.FK_PP_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setFkPpAttachmentId(String fkPpAttachmentId) {
        this.fkPpAttachmentId = fkPpAttachmentId == null ? null : fkPpAttachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.EXPERT_EVIDENCE
     *
     * @return the value of FI_FOREIGNER.EXPERT_EVIDENCE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getExpertEvidence() {
        return expertEvidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.EXPERT_EVIDENCE
     *
     * @param expertEvidence the value for FI_FOREIGNER.EXPERT_EVIDENCE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setExpertEvidence(Integer expertEvidence) {
        this.expertEvidence = expertEvidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.FK_EE_ATTACHMENT_ID
     *
     * @return the value of FI_FOREIGNER.FK_EE_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getFkEeAttachmentId() {
        return fkEeAttachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.FK_EE_ATTACHMENT_ID
     *
     * @param fkEeAttachmentId the value for FI_FOREIGNER.FK_EE_ATTACHMENT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setFkEeAttachmentId(String fkEeAttachmentId) {
        this.fkEeAttachmentId = fkEeAttachmentId == null ? null : fkEeAttachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.FK_RP_PERMIT_ID
     *
     * @return the value of FI_FOREIGNER.FK_RP_PERMIT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getFkRpPermitId() {
        return fkRpPermitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.FK_RP_PERMIT_ID
     *
     * @param fkRpPermitId the value for FI_FOREIGNER.FK_RP_PERMIT_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setFkRpPermitId(String fkRpPermitId) {
        this.fkRpPermitId = fkRpPermitId == null ? null : fkRpPermitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.FK_INVITATION_ID
     *
     * @return the value of FI_FOREIGNER.FK_INVITATION_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getFkInvitationId() {
        return fkInvitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.FK_INVITATION_ID
     *
     * @param fkInvitationId the value for FI_FOREIGNER.FK_INVITATION_ID
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setFkInvitationId(String fkInvitationId) {
        this.fkInvitationId = fkInvitationId == null ? null : fkInvitationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.FK_BEUSE
     *
     * @return the value of FI_FOREIGNER.FK_BEUSE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getFkBeuse() {
        return fkBeuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.FK_BEUSE
     *
     * @param fkBeuse the value for FI_FOREIGNER.FK_BEUSE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setFkBeuse(Integer fkBeuse) {
        this.fkBeuse = fkBeuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.IS_HERE
     *
     * @return the value of FI_FOREIGNER.IS_HERE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getIsHere() {
        return isHere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.IS_HERE
     *
     * @param isHere the value for FI_FOREIGNER.IS_HERE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setIsHere(Integer isHere) {
        this.isHere = isHere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.STATUS
     *
     * @return the value of FI_FOREIGNER.STATUS
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.STATUS
     *
     * @param status the value for FI_FOREIGNER.STATUS
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.CREATE_DATE
     *
     * @return the value of FI_FOREIGNER.CREATE_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.CREATE_DATE
     *
     * @param createDate the value for FI_FOREIGNER.CREATE_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.EDIT_DATE
     *
     * @return the value of FI_FOREIGNER.EDIT_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.EDIT_DATE
     *
     * @param editDate the value for FI_FOREIGNER.EDIT_DATE
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.CREATE_USER
     *
     * @return the value of FI_FOREIGNER.CREATE_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.CREATE_USER
     *
     * @param createUser the value for FI_FOREIGNER.CREATE_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_FOREIGNER.EDIT_USER
     *
     * @return the value of FI_FOREIGNER.EDIT_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_FOREIGNER.EDIT_USER
     *
     * @param editUser the value for FI_FOREIGNER.EDIT_USER
     *
     * @mbggenerated Tue Oct 22 15:45:16 CST 2013
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser == null ? null : editUser.trim();
    }
}