package cn.com.jnpc.foreign.po;

import java.util.Date;

public class FiInvitation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String invitationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.FK_ATTACHMENT_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String fkAttachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.IS_USE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.STAY_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String stayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.GOBACK_TIMES
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String gobackTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.ARRIVED_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date arrivedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.LEAVING_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date leavingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INVITATION.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String editUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.ID
     *
     * @return the value of FI_INVITATION.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.ID
     *
     * @param id the value for FI_INVITATION.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.INVITATION_ID
     *
     * @return the value of FI_INVITATION.INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getInvitationId() {
        return invitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.INVITATION_ID
     *
     * @param invitationId the value for FI_INVITATION.INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setInvitationId(String invitationId) {
        this.invitationId = invitationId == null ? null : invitationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.FK_ATTACHMENT_ID
     *
     * @return the value of FI_INVITATION.FK_ATTACHMENT_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getFkAttachmentId() {
        return fkAttachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.FK_ATTACHMENT_ID
     *
     * @param fkAttachmentId the value for FI_INVITATION.FK_ATTACHMENT_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setFkAttachmentId(String fkAttachmentId) {
        this.fkAttachmentId = fkAttachmentId == null ? null : fkAttachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.IS_USE
     *
     * @return the value of FI_INVITATION.IS_USE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.IS_USE
     *
     * @param isUse the value for FI_INVITATION.IS_USE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.STAY_TIME
     *
     * @return the value of FI_INVITATION.STAY_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getStayTime() {
        return stayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.STAY_TIME
     *
     * @param stayTime the value for FI_INVITATION.STAY_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setStayTime(String stayTime) {
        this.stayTime = stayTime == null ? null : stayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.GOBACK_TIMES
     *
     * @return the value of FI_INVITATION.GOBACK_TIMES
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getGobackTimes() {
        return gobackTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.GOBACK_TIMES
     *
     * @param gobackTimes the value for FI_INVITATION.GOBACK_TIMES
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setGobackTimes(String gobackTimes) {
        this.gobackTimes = gobackTimes == null ? null : gobackTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.ARRIVED_DATE
     *
     * @return the value of FI_INVITATION.ARRIVED_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getArrivedDate() {
        return arrivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.ARRIVED_DATE
     *
     * @param arrivedDate the value for FI_INVITATION.ARRIVED_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setArrivedDate(Date arrivedDate) {
        this.arrivedDate = arrivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.LEAVING_DATE
     *
     * @return the value of FI_INVITATION.LEAVING_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getLeavingDate() {
        return leavingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.LEAVING_DATE
     *
     * @param leavingDate the value for FI_INVITATION.LEAVING_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setLeavingDate(Date leavingDate) {
        this.leavingDate = leavingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.STATUS
     *
     * @return the value of FI_INVITATION.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.STATUS
     *
     * @param status the value for FI_INVITATION.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.CREATE_DATE
     *
     * @return the value of FI_INVITATION.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.CREATE_DATE
     *
     * @param createDate the value for FI_INVITATION.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.EDIT_DATE
     *
     * @return the value of FI_INVITATION.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.EDIT_DATE
     *
     * @param editDate the value for FI_INVITATION.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.CREATE_USER
     *
     * @return the value of FI_INVITATION.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.CREATE_USER
     *
     * @param createUser the value for FI_INVITATION.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INVITATION.EDIT_USER
     *
     * @return the value of FI_INVITATION.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INVITATION.EDIT_USER
     *
     * @param editUser the value for FI_INVITATION.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser == null ? null : editUser.trim();
    }
}