package cn.com.jnpc.foreign.po;

import java.util.Date;

public class FiInout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.END_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.FK_FOREIGNER_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String fkForeignerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.FK_INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String fkInvitationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.TYPE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.CONTENT
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_INOUT.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    private String editUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.ID
     *
     * @return the value of FI_INOUT.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.ID
     *
     * @param id the value for FI_INOUT.ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.BEGIN_TIME
     *
     * @return the value of FI_INOUT.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getBeginTime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.BEGIN_TIME
     *
     * @param begIntegerime the value for FI_INOUT.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setBeginTime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.END_TIME
     *
     * @return the value of FI_INOUT.END_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.END_TIME
     *
     * @param endTime the value for FI_INOUT.END_TIME
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.FK_FOREIGNER_ID
     *
     * @return the value of FI_INOUT.FK_FOREIGNER_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getFkForeignerId() {
        return fkForeignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.FK_FOREIGNER_ID
     *
     * @param fkForeignerId the value for FI_INOUT.FK_FOREIGNER_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setFkForeignerId(String fkForeignerId) {
        this.fkForeignerId = fkForeignerId == null ? null : fkForeignerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.FK_INVITATION_ID
     *
     * @return the value of FI_INOUT.FK_INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getFkInvitationId() {
        return fkInvitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.FK_INVITATION_ID
     *
     * @param fkInvitationId the value for FI_INOUT.FK_INVITATION_ID
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setFkInvitationId(String fkInvitationId) {
        this.fkInvitationId = fkInvitationId == null ? null : fkInvitationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.TYPE
     *
     * @return the value of FI_INOUT.TYPE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.TYPE
     *
     * @param type the value for FI_INOUT.TYPE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.CONTENT
     *
     * @return the value of FI_INOUT.CONTENT
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.CONTENT
     *
     * @param content the value for FI_INOUT.CONTENT
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.STATUS
     *
     * @return the value of FI_INOUT.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.STATUS
     *
     * @param status the value for FI_INOUT.STATUS
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.CREATE_DATE
     *
     * @return the value of FI_INOUT.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.CREATE_DATE
     *
     * @param createDate the value for FI_INOUT.CREATE_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.CREATE_USER
     *
     * @return the value of FI_INOUT.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.CREATE_USER
     *
     * @param createUser the value for FI_INOUT.CREATE_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.EDIT_DATE
     *
     * @return the value of FI_INOUT.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.EDIT_DATE
     *
     * @param editDate the value for FI_INOUT.EDIT_DATE
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_INOUT.EDIT_USER
     *
     * @return the value of FI_INOUT.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_INOUT.EDIT_USER
     *
     * @param editUser the value for FI_INOUT.EDIT_USER
     *
     * @mbggenerated Sun Sep 22 22:28:01 CST 2013
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser == null ? null : editUser.trim();
    }
}