package cn.com.jnpc.foreign.po;

import java.util.Date;

public class FiMiddle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.FK_INVITATION_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String fkInvitationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.FK_PERSON_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String fkPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.FK_PERSON_PPID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String fkPersonPpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.CREATE_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.CREATE_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.EDIT_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String editUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.EDIT_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.WORK
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String work;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.WORK_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String workAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.LIVING_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String livingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FI_MIDDLE.DEFER_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    private String deferId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.ID
     *
     * @return the value of FI_MIDDLE.ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.ID
     *
     * @param id the value for FI_MIDDLE.ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.FK_INVITATION_ID
     *
     * @return the value of FI_MIDDLE.FK_INVITATION_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getFkInvitationId() {
        return fkInvitationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.FK_INVITATION_ID
     *
     * @param fkInvitationId the value for FI_MIDDLE.FK_INVITATION_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setFkInvitationId(String fkInvitationId) {
        this.fkInvitationId = fkInvitationId == null ? null : fkInvitationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.FK_PERSON_ID
     *
     * @return the value of FI_MIDDLE.FK_PERSON_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getFkPersonId() {
        return fkPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.FK_PERSON_ID
     *
     * @param fkPersonId the value for FI_MIDDLE.FK_PERSON_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setFkPersonId(String fkPersonId) {
        this.fkPersonId = fkPersonId == null ? null : fkPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.FK_PERSON_PPID
     *
     * @return the value of FI_MIDDLE.FK_PERSON_PPID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getFkPersonPpid() {
        return fkPersonPpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.FK_PERSON_PPID
     *
     * @param fkPersonPpid the value for FI_MIDDLE.FK_PERSON_PPID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setFkPersonPpid(String fkPersonPpid) {
        this.fkPersonPpid = fkPersonPpid == null ? null : fkPersonPpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.CREATE_DATE
     *
     * @return the value of FI_MIDDLE.CREATE_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.CREATE_DATE
     *
     * @param createDate the value for FI_MIDDLE.CREATE_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.CREATE_USER
     *
     * @return the value of FI_MIDDLE.CREATE_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.CREATE_USER
     *
     * @param createUser the value for FI_MIDDLE.CREATE_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.EDIT_USER
     *
     * @return the value of FI_MIDDLE.EDIT_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getEditUser() {
        return editUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.EDIT_USER
     *
     * @param editUser the value for FI_MIDDLE.EDIT_USER
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setEditUser(String editUser) {
        this.editUser = editUser == null ? null : editUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.EDIT_DATE
     *
     * @return the value of FI_MIDDLE.EDIT_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.EDIT_DATE
     *
     * @param editDate the value for FI_MIDDLE.EDIT_DATE
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.WORK
     *
     * @return the value of FI_MIDDLE.WORK
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.WORK
     *
     * @param work the value for FI_MIDDLE.WORK
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.WORK_ADDRESS
     *
     * @return the value of FI_MIDDLE.WORK_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getWorkAddress() {
        return workAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.WORK_ADDRESS
     *
     * @param workAddress the value for FI_MIDDLE.WORK_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress == null ? null : workAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.LIVING_ADDRESS
     *
     * @return the value of FI_MIDDLE.LIVING_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getLivingAddress() {
        return livingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.LIVING_ADDRESS
     *
     * @param livingAddress the value for FI_MIDDLE.LIVING_ADDRESS
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setLivingAddress(String livingAddress) {
        this.livingAddress = livingAddress == null ? null : livingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FI_MIDDLE.DEFER_ID
     *
     * @return the value of FI_MIDDLE.DEFER_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public String getDeferId() {
        return deferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FI_MIDDLE.DEFER_ID
     *
     * @param deferId the value for FI_MIDDLE.DEFER_ID
     *
     * @mbggenerated Tue Sep 24 10:41:03 CST 2013
     */
    public void setDeferId(String deferId) {
        this.deferId = deferId == null ? null : deferId.trim();
    }
}